name: Update Formulas
author: Milad Irannejad
description: GitHub action for updating Homebrew formulas.
inputs:
  github_token:
    description: The GitHub token provided in github context or GITHUB_TOKEN secret.
    required: true
outputs:
  output:
    description: TBD.
runs:
  using: node12
  main: dist/index.js
branding:
  icon: grid
  color: yellow
