name: Update Formulas
author: Milad Irannejad
description: GitHub action for updating Homebrew formulas.
inputs:
  input:
    description: TBD.
    required: true
outputs:
  output:
    description: TBD.
runs:
  using: node12
  main: dist/index.js
branding:
  icon: grid
  color: yellow
