name: Update
on:
  schedule:
    # https://crontab.guru
    # * is a special character in YAML, so this string needs to be quoted
    - cron: '0 8 * * *'
jobs:
  formulas:
    name: Formulas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Formulas
        uses: ./.github/actions/update-formulas
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
